# Configure the analyzer which statically analyzes Dart code.
#
# Invoke the analyzer from the command line:
#
# `flutter analyze`

# Activate recommended lints for Flutter apps, packages, and plugins
# designed to encourage good coding practices.

# include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - ignore/**

custom_lint:
  rules:
    - import_order_lint
  options:
    import_order_lint:
      project_name: rattle

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    require_trailing_commas: true
    directives_ordering: false
