/// A widget to build the common single image based pages.
//
// Time-stamp: "Tuesday 2026-01-06 14:16:05 +1100 Graham Williams"
//
/// Copyright (C) 2024-2026, Togaware Pty Ltd
///
/// Licensed under the GNU General Public License, Version 3 (the "License");
///
/// License: https://opensource.org/license/gpl-3-0
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
// details.
//
// You should have received a copy of the GNU General Public License along with
// this program.  If not, see <https://opensource.org/license/gpl-3-0>.
///
/// Authors: Graham Williams, Yixiang Yin, Zheyuan Xu

library;

// 20241228 gjw The rendering of SVG fails if the SVG contains filter
// elements. This is the case for images generated by plot with method=graph
// from arulesViz.

import 'dart:async';
import 'dart:io';
import 'dart:math' as math;

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import 'package:flutter_markdown/flutter_markdown.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:gap/gap.dart';
import 'package:markdown_tooltip/markdown_tooltip.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:url_launcher/url_launcher.dart';

import 'package:rattle/constants/sunken_box_decoration.dart';
import 'package:rattle/constants/temp_dir.dart';
import 'package:rattle/providers/settings.dart';
import 'package:rattle/utils/save_plot.dart';
import 'package:rattle/utils/show_image_dialog.dart';

/// The [path] is required. It is the path to a SVG or PNG file to display in
/// the app and to open/save externally. If [display] is also provided then this
/// will be a PNG that is displayed in the app, while the [path] is an SVG to
/// open/save externally. This functionality was added to support the case where
/// an SVG includes unsupported features (e.g., filter) that result in a black
/// rectangle displayed. The PNG will be displayed in the app but external
/// viewers get the SVG.

class ImagePage extends ConsumerWidget {
  final String title;
  final String path;
  final String? display;

  const ImagePage({
    super.key,
    required this.title,
    required this.path,
    this.display,
  });

  // Load the image bytes from the specified file path.
  //
  // This method attempts to read the image file as bytes. If using the display
  // parameter, it will load from [display], otherwise it uses the original SVG
  // path.
  //
  // Returns a [Future] that completes with the image bytes as a [Uint8List] if
  // the file exists, or `null` if the file does not exist.

  Future<Uint8List?> _loadImageBytes() async {
    try {
      final displayPath = display ?? path;

      // Wait for the file to exist.

      final file = File(displayPath);
      int retryCount = 0;
      while (!await file.exists() && retryCount < 5) {
        await Future.delayed(const Duration(seconds: 1));

        retryCount++;
      }

      if (await file.exists()) {
        return await file.readAsBytes();
      } else {
        if (kDebugMode) {
          print('Image file not found: $displayPath');
        }

        return null;
      }
    } catch (e) {
      if (kDebugMode) {
        print('Error loading image: $e');
      }

      return null;
    }
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // Clear the image cache.

    imageCache.clear();
    imageCache.clearLiveImages();

    return FutureBuilder<Uint8List?>(
      future: _loadImageBytes(),
      builder: (BuildContext context, AsyncSnapshot<Uint8List?> snapshot) {
        var bytes = snapshot.data;
        if (snapshot.hasError) {
          return Center(child: Text('Error: ${snapshot.error}'));
        } else if (snapshot.connectionState == ConnectionState.waiting) {
          return const Center(child: CircularProgressIndicator());
        } else if (bytes == null || bytes.isEmpty) {
          return const Center(
            child: Text(
              'Image not (yet) available',
              style: TextStyle(
                fontSize: 20,
                fontWeight: FontWeight.bold,
                color: Colors.redAccent,
              ),
            ),
          );
        } else {
          // Determine which image to display based on file extension.

          final bool isSvg = (display ?? path).toLowerCase().endsWith('.svg');

          return Container(
            decoration: sunkenBoxDecoration,
            width: double.infinity,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  // 20240726 gjw Ensure the Save button is aligned at the top.
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // 20240726 gjw Remove the Flexible for now. Perhaps avoid
                    // long text in the Image Page for now. Save button was
                    // not getting pushed all the way to the right after
                    // adding Flexible.
                    //
                    // 20240725 gjw Introduce the Flexible wrapper to avoid the markdown
                    // text overflowing to the elevarted Export
                    // button.
                    MarkdownBody(
                      data: wordWrap(title),
                      selectable: true,
                      onTapLink: (text, href, title) {
                        final Uri url = Uri.parse(href ?? '');
                        launchUrl(url);
                      },
                    ),
                    const Spacer(),
                    MarkdownTooltip(
                      message: '''

                        **Enlarge**

                        Tap here to view the plot enlarged to the
                        maximimum size within the app.

                        ''',
                      child: IconButton(
                        icon: const Icon(
                          Icons.zoom_out_map,
                          color: Colors.blue,
                        ),
                        onPressed: () {
                          // Determine which image to display. If a [display]
                          // is provided then that overrides [path]. (gjw
                          // 20250419)

                          final bool isSvg =
                              (display ?? path).toLowerCase().endsWith('.svg');
                          showImageDialog(context, bytes, isSvg: isSvg);
                        },
                      ),
                    ),
                    MarkdownTooltip(
                      message: '''

                        **Open**

                        Tap here to open the plot in a separate window
                        to the Rattle app itself. This allows you to retain a
                        view of the plot while you navigate through other plots
                        and analyses. If you choose the external app to be
                        **Inkscape**, for example, then you can edit the plot,
                        including the text, colours, etc. Note that Inkscape can
                        be a little slow to startup. The choice of app depends
                        on your operating system settings and can be overriden
                        in the Rattle **Settings**.

                        ''',
                      child: IconButton(
                        icon: const Icon(
                          Icons.open_in_new,
                          color: Colors.blue,
                        ),
                        onPressed: () async {
                          // We always display the [path] externally,
                          // irrespective of whether we have a [display],
                          // which is intended for in-app use only.

                          final bool isSvg = path.toLowerCase().endsWith(
                                '.svg',
                              );

                          // Generate a unique file name for the new file in
                          // the temporary directory with the correct
                          // extension. We do this since the original filename
                          // will be overwritten by a new plot within Rattle, thus
                          // losing the displayed file. 20250807 gjw

                          String extension = isSvg ? 'svg' : 'png';
                          String fileName =
                              'plot_${math.Random().nextInt(10000)}.$extension';
                          File tempFile = File('$tempDir/$fileName');

                          // Copy the original file to the temporary file.

                          await File(path).copy(tempFile.path);

                          // Get the image viewer app from SharedPreferences
                          // or use the provider default if not set.

                          final prefs = await SharedPreferences.getInstance();
                          final savedImageViewer = prefs.getString(
                            'imageViewerApp',
                          );

                          // If the shared preferences image viewer app is
                          // null(not set), use the provider default.

                          final imageViewerApp = savedImageViewer ??
                              ref.read(imageViewerSettingProvider);

                          Platform.isWindows
                              ? Process.run(
                                  imageViewerApp!,
                                  [
                                    path,
                                  ],
                                  runInShell: true,
                                )
                              : Process.run(imageViewerApp!, [tempFile.path]);
                        },
                      ),
                    ),
                    MarkdownTooltip(
                      message: '''

                        **Save**

                        Tap here to save the plot in your preferred
                        format (**svg**, **pdf**, or **png**). You can directly
                        choose your desired format by replacing the default
                        *svg* filename extension with either *pdf* or *png*. The
                        file is saved to your local storage. Perfect for
                        including in reports or keeping for future
                        reference. The SVG format is particularly convenient as
                        you can edit all details of the plot with an application
                        like **Inkscape**.

                        ''',
                      child: IconButton(
                        icon: const Icon(Icons.save, color: Colors.blue),
                        onPressed: () => savePlot(context, path),
                      ),
                    ),
                    const Gap(5),
                  ],
                ),
                const Gap(5),

                // Display the plot as the main body of the widget, taking
                // all of the space that the title above it leaves.
                //
                // 20260815 gjw The viewing area was previously a square with
                // sides of the smaller of the available width and 60% of the
                // window height. Our plots are generated by R as 10 by 7
                // inches (the `svg()` calls in `assets/r/`), so squaring the
                // viewing area fitted them by their width and left the plot
                // some 30% smaller than the space allowed, with the text
                // that much less readable and a wide empty margin either
                // side.
                //
                // Filling the space instead, and leaving [BoxFit.contain] to
                // scale the plot to its own aspect ratio, makes the plot as
                // large as it can be. A square plot still fits, scaled to
                // the height, and is centred within the width.
                //
                // The height has to come from [Expanded] rather than from
                // the window height, which is what the square viewing area
                // used. The window is always taller than the space left here
                // below the title, so a plot sized to the window ran off the
                // bottom of the page, losing the x axis label and the Rattle
                // timestamp footer. That went unnoticed while the plot was
                // square, since fitting a 10 by 7 plot by its width left it
                // well short of filling the too tall viewing area.
                //
                // [Expanded] needs the page to have a bounded height, which
                // it does: `widgets/page_viewer.dart` puts the [PageView] in
                // an [Expanded] of its own. The plot can therefore never
                // overflow, and the enclosing [SingleChildScrollView] that
                // used to absorb the overflow is no longer needed.

                // The [SizedBox] takes the full width so that the plot is
                // centred horizontally by [BoxFit.contain]. Without it the
                // plot is left aligned: the [CrossAxisAlignment.start] of the
                // enclosing [Column] passes loose width constraints to its
                // children, so the plot sizes to its own width, having been
                // fitted to the height, rather than to the width of the page.
                // (gjw 20260815)

                Expanded(
                  child: SizedBox(
                    width: double.infinity,
                    child: InteractiveViewer(
                      maxScale: 5,
                      alignment: Alignment.center,
                      child: isSvg
                          ? SvgPicture.memory(bytes, fit: BoxFit.contain)
                          : Image.memory(bytes, fit: BoxFit.contain),
                    ),
                  ),
                ),
              ],
            ),
          );
        }
      },
    );
  }
}
