/// General cleanup of strings from the R console.
//
// Time-stamp: <Tuesday 2024-08-20 13:47:14 +1000 Graham Williams>
//
/// Copyright (C) 2024, Togaware Pty Ltd
///
/// Licensed under the GNU General Public License, Version 3 (the "License");
///
/// License: https://www.gnu.org/licenses/gpl-3.0.en.html
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
// details.
//
// You should have received a copy of the GNU General Public License along with
// this program.  If not, see <https://www.gnu.org/licenses/>.
///
/// Authors: Graham Williams

library;

// Group imports by dart, flutter, packages, local. Then alphabetically.

String cleanString(String txt) {
  // On moving to pty I was getting lots of escapes.

  txt = txt.replaceAll('', '');
  txt = txt.replaceAll('\r', '');

  // 20240812 gjw These seem to be in glimpse() output making the data type
  // italic. Noticed this on Anushka's Windows 10 desktop. But not on my Windows
  // 11 desktop.

  txt = txt.replaceAll('[3m[38;2;148;148;148m', '');
  txt = txt.replaceAll('[23m[m', '');

  // 20240820 gjw These were noticed on Mukund's Windows OS.

  txt = txt.replaceAll('[38;5;246[3mm', '');
  txt = txt.replaceAll('[m', '');
  txt = txt.replaceAll('[245;80H', '');

  // 20240815 gjw Generated by skimr.

  txt = txt.replaceAll('[38;5;250m', '');
  txt = txt.replaceAll('[4m', '');
  txt = txt.replaceAll('[24m', '');

  txt = txt.replaceAll('[3m[38;5;246m', '');
  txt = txt.replaceAll('[?2004l', '');
  txt = txt.replaceAll('[39m[23m', '');
  txt = txt.replaceAll('[?2004h', '');
  txt = txt.replaceAll('[A', '');
  txt = txt.replaceAll('[C', '');
  txt = txt.replaceAll('[?25h', '');
  txt = txt.replaceAll('[K', '');
  txt = txt.replaceAll(RegExp(r'\[3.m'), '');

  // 20240602 gjw Remove the `[3m[90m` that appears in the output now. Not
  // sure where that has come from or when it sneaked in.

  txt = txt.replaceAll('[3m[90m', '');

  // 20240810 Noticing these on Windows.

  txt = txt.replaceAll(RegExp(r'\[\d{1,2}[CX]'), '');

  return txt;
}
