#include "my_application.h"

#include <flutter_linux/flutter_linux.h>
#ifdef GDK_WINDOWING_X11
#include <gdk/gdkx.h>
#endif

#include "flutter/generated_plugin_registrant.h"

struct _MyApplication {
  GtkApplication parent_instance;
  char** dart_entrypoint_arguments;
};

G_DEFINE_TYPE(MyApplication, my_application, GTK_TYPE_APPLICATION)

// Implements GApplication::activate.
static void my_application_activate(GApplication* application) {
  MyApplication* self = MY_APPLICATION(application);
  GtkWindow* window =
      GTK_WINDOW(gtk_application_window_new(GTK_APPLICATION(application)));

  // Use a header bar when running in GNOME as this is the common style used
  // by applications and is the setup most users will be using (e.g. Ubuntu
  // desktop).
  // If running on X and not using GNOME then just use a traditional title bar
  // in case the window manager does more exotic layout, e.g. tiling.
  // If running on Wayland assume the header bar will work (may need changing
  // if future cases occur).
  gboolean use_header_bar = TRUE;
#ifdef GDK_WINDOWING_X11
  GdkScreen* screen = gtk_window_get_screen(window);
  if (GDK_IS_X11_SCREEN(screen)) {
    const gchar* wm_name = gdk_x11_screen_get_window_manager_name(screen);
    if (g_strcmp0(wm_name, "GNOME Shell") != 0) {
      use_header_bar = FALSE;
    }
  }
#endif
  if (use_header_bar) {
    GtkHeaderBar* header_bar = GTK_HEADER_BAR(gtk_header_bar_new());
    gtk_widget_show(GTK_WIDGET(header_bar));
    gtk_header_bar_set_title(header_bar, "rattle");
    gtk_header_bar_set_show_close_button(header_bar, TRUE);
    gtk_window_set_titlebar(window, GTK_WIDGET(header_bar));
  } else {
    gtk_window_set_title(window, "rattle");
  }

  gtk_window_set_default_size(window, 1300, 850);
  gtk_widget_show(GTK_WIDGET(window));

  g_autoptr(FlDartProject) project = fl_dart_project_new();
  fl_dart_project_set_dart_entrypoint_arguments(project, self->dart_entrypoint_arguments);

  // 20260815 gjw Render with Skia rather than Impeller.
  //
  // Flutter 3.47.0 made Impeller the default renderer on Linux (engine commit
  // fa137457bad, "Turn linux impeller on by default", 2026-06-24). Our plots
  // are SVG generated by R and displayed through flutter_svg, and Impeller
  // renders them noticeably worse than Skia: the axis labels and plot titles
  // become blurry and the thin grid lines alias badly, to the point where the
  // box plot title is hardly readable. Nothing in Rattle changed - the same
  // Rattle version renders crisply on the older Flutter.
  //
  // Two Impeller behaviours on Linux explain it, and neither can be tuned:
  // `fl_engine.cc` always appends `--impeller-use-sdfs` so glyphs go through
  // signed distance field rendering, and that switch is read with `HasOption`,
  // a presence check, so a `=false` value does not disable it; and line
  // antialiasing is off by default, its `--impeller-antialias-lines` switch
  // still being described upstream as experimental.
  //
  // The `FLUTTER_ENGINE_SWITCHES` environment variables can turn Impeller off
  // for a debug or profile run, but they are compiled out of release builds,
  // so the choice has to be made here to reach our users.
  //
  // This is a stopgap. Skia is on its way out of the engine, so revisit when
  // Impeller's text and line rendering improves, or if a future Flutter drops
  // Skia entirely. See ARCHITECTURE.md for the full story.

  fl_dart_project_set_enable_impeller(project, FALSE);

  FlView* view = fl_view_new(project);
  gtk_widget_show(GTK_WIDGET(view));
  gtk_container_add(GTK_CONTAINER(window), GTK_WIDGET(view));

  fl_register_plugins(FL_PLUGIN_REGISTRY(view));

  gtk_widget_grab_focus(GTK_WIDGET(view));
}

// Implements GApplication::local_command_line.
static gboolean my_application_local_command_line(GApplication* application, gchar*** arguments, int* exit_status) {
  MyApplication* self = MY_APPLICATION(application);

  // 20260817 gjw Issue #1179. Report the version and stop here, before the
  // window is created in my_application_activate() above. `lib/main.dart`
  // answers --version too, for the other desktops, but by the time Dart runs
  // the window has been created and shown, and the user asking a command line
  // program its version sees it flash up and vanish. APP_VERSION comes from
  // pubspec.yaml by way of CMakeLists.txt.

  for (gchar** arg = *arguments + 1; arg != nullptr && *arg != nullptr; arg++) {
    if (g_strcmp0(*arg, "--version") == 0 || g_strcmp0(*arg, "-v") == 0) {
      g_print("%s %s\n", APP_BINARY_NAME, APP_VERSION);
      *exit_status = 0;

      return TRUE;
    }
  }

  // Strip out the first argument as it is the binary name.
  self->dart_entrypoint_arguments = g_strdupv(*arguments + 1);

  g_autoptr(GError) error = nullptr;
  if (!g_application_register(application, nullptr, &error)) {
     g_warning("Failed to register: %s", error->message);
     *exit_status = 1;
     return TRUE;
  }

  g_application_activate(application);
  *exit_status = 0;

  return TRUE;
}

// Implements GObject::dispose.
static void my_application_dispose(GObject* object) {
  MyApplication* self = MY_APPLICATION(object);
  g_clear_pointer(&self->dart_entrypoint_arguments, g_strfreev);
  G_OBJECT_CLASS(my_application_parent_class)->dispose(object);
}

static void my_application_class_init(MyApplicationClass* klass) {
  G_APPLICATION_CLASS(klass)->activate = my_application_activate;
  G_APPLICATION_CLASS(klass)->local_command_line = my_application_local_command_line;
  G_OBJECT_CLASS(klass)->dispose = my_application_dispose;
}

static void my_application_init(MyApplication* self) {}

MyApplication* my_application_new() {
  return MY_APPLICATION(g_object_new(my_application_get_type(),
                                     "application-id", APPLICATION_ID,
                                     "flags", G_APPLICATION_NON_UNIQUE,
                                     nullptr));
}
