# 20240803
#
# It runs R if we run from /snap/rattle/current/rattle
#
# It fails to run R is started from /snap/bin/rattle?

name: rattle
version: 6.2.38
summary: Rattle Next Generation Data Science
description: Rattle is the data scientists toolkit.

confinement: strict
base: core22
grade: stable

#slots:
#  dbus-rattle:
#    interface: dbus
#    bus: session
#    name: com.togaware.rattle
    
apps:
  rattle:
    command: rattle
    extensions: [gnome] # gnome includes the libraries required by flutter
    plugs:
    - network
    - home
    - removable-media
    - system-files
#    slots:
#      - dbus-rattle

parts:
  rattle:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
    stage-packages:
      - r-recommended

plugs:
  system-files:
    interface: system-files
    read:
      - /usr/bin/R
    write:
      - /usr/lib/R  # Allows writing to the R path within the snap
      
environment:
  LIBGL_ALWAYS_SOFTWARE: 1  # Ensures compatibility with different systems
